### ISSUE TITLE
think about how to make library binding generic

### ISSUE THREAD

**Issue by tzigiannis** [tzigiannis/encryptio#12]
Timeboxed: 5 hours

--> talk to Mr. Eggendorfer with solution and coordinate next steps

**Comment by Morn98** [comment]
Discussed at 02.11.2022. 

-> Idea discarded because of the problem that python encryption libraries use **different** module, class and function names. Besides this fact, the parameter call of a function could differ aswell. 

-> Further ideas will be discussed with Mr. Eggendorfer.
