### ISSUE TITLE
create collaborative word file for documentation, add user and update readme with link to collaborative word file. --> Set Write Permissions correct

### ISSUE THREAD

**Issue by Morn98** [tzigiannis/encryptio#6]
User: 

moritz.nentwig@bwedu.de

https://support.microsoft.com/en-us/office/collaborate-in-word-b3d7f2af-c6e9-46e7-96a7-dabda4423dd7

**Comment by tzigiannis** [comment]
@Morn9 Should we really have a link in the readme? what for?
